#!/bin/bash
#kasutaja loomine failist 
#echo "Kasutajate loomine kasutades faili kasutaja_nimed"
#fail, kust nimed võetakse tuleb veidike modifitseerida (algab tühja reaga, siis nimi, uuest tühi rida, siis uuest nimi
#while read -r line; do ./kasutaja_lisamine.sh; done < kasutaja_nimed

#teine lahendus
if [ $# -ne 1 ]; then
	echo "Kasutusjuhend: $0 failinimi"
else
	failinimi=$1
	if [ -f $failinimi -a -r $failinimi ]; then
		echo "Fail on korras"
		for nimi in $(cat $failinimi)
		do
			sh lisa_kasutaja $nimi
		done
	else
		echo "Probleem failiga $failinimi"
	fi
fi
